[package]
name = "rust_kdtree"
version = "0.1.0"
authors = ["varoon <pazhyanurv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "2.0.1"

[dev-dependencies]
proptest = "0.9"
